### PR TITLE
ui. show installed packages and improve software center

### PR DESCRIPTION
**Pull request by federicoballarini**
Refer to https://github.com/NethServer/dev/issues/5950

### CODE REVIEW

**Comment by federicoballarini** [comment]
Next steps:
- installed packages modal
- insert language strings

**Comment by gsanchietti** [comment]
This is a preview:
Screenshot from 2019-11-25 15-47-13

I think there are still some issue:
- the number on the right is not the release, but the full version
- previously, the current installed version was installed, now it's missing
- the button to open the list of installed packages works very good, but it's the in the wrong position: all existing buttons are relative to updates. I think the button for installed packages should be moved somewhere else

**Comment by federicoballarini** [comment]
_> the number on the right is not the release, but the full version_
Yes, we can correct it.

_> previously, the current installed version was installed, now it's missing_
I removed it, because of the new "Installed" button, but we can add it on the right of Full Version like:(Current: 2.4.0-1.ns7)

_> the button to open the list of installed packages works very good, but it's the in the wrong position: all existing buttons are relative to updates. I think the button for installed packages should be moved somewhere else_
I can try to find another place.

Do you think it's better to revert all my commits and push only 2 new commit?

**Comment by edospadoni** [comment]
Here my reviews: 
1. The console show this error:
```
vue.runtime.esm.js?2b0e:619 [Vue warn]: Error in render: "TypeError: Cannot read property 'length' of undefined"
```

You have to declare a `packages: []` on line `562`, under the `updates` object.

----

2. When opening the Updates accordion, at the bottom you should show also the correct number of base system update, like for nethserver. The label says **2** updates, but the modal shows **10** updates
mismatch

----

3. I agree with @gsanchietti, you should move the `Installed` button somewhere else, maybe in the `Applications` page, with all installed software, but I'm not sure :thinking: . Maybe some mockups should helps

----


4. I like this idea to keep the current version
> I removed it, because of the new "Installed" button, but we can add it on the right of Full Version like:(Current: 2.4.0-1.ns7)

**Comment by federicoballarini** [comment]
I will close this PR and opened new one without unuseful commits.

**Pull request closed without merging**
