### PR TITLE
ui. fix storage info view

### PR DESCRIPTION
**Pull request by federicoballarini**
Fixed storage info bar view issue
Refer to https://github.com/NethServer/dev/issues/6168

### CODE REVIEW

**Comment by federicoballarini** [comment]
I think @gsanchietti and @edospadoni can review.

**Comment by gsanchietti** [comment]
Sorry, but I really do not know what the patch does.
Let's see if someone else with more skill can help here :)

**Comment by federicoballarini** [comment]
> Sorry, but I really do not know what the patch does.

This should allow to use inline style property into a popover. Otherwise it will be blocked. And this is the cause of the bug: the inline style is deleted if you check the code.

**Comment by edospadoni** [comment]
> I think @gsanchietti and @edospadoni can review.

The patch is cool :+1: Great job @federicoballarini

**Pull request merged**
