### PR TITLE
ui. improve modal view

### PR DESCRIPTION
**Pull request by federicoballarini**
Changed into network, services and backup.
Also added `modal-lg` class for service status, backup log and certificate show.
Refer to https://github.com/NethServer/dev/issues/5965

### CODE REVIEW

**Comment by edospadoni** [comment]
There is no need to add `modal-lg` class inside modal. This PR must only change the labels.

**Comment by federicoballarini** [comment]
@edospadoni Changed. But a question: you don't want to change modals size or I have to split it into another PR? Because in these 3 cases it can be helpful to have `modal-lg` size (backup logs, service status, show certificate).

**Comment by edospadoni** [comment]
> @edospadoni Changed. But a question: you don't want to change modals size or I have to split it into another PR? Because in these 3 cases it can be helpful to have `modal-lg` size (backup logs, service status, show certificate).

Could be useful, but we don't have any `modal-lg` inside cockpit core or modules. We can evaluate a restyling in all modules, but next time.

**Comment by federicoballarini** [comment]
Except the new Software Center ^_^

**Pull request merged**
