### PR TITLE
ui. show total of users and groups

### PR DESCRIPTION
**Pull request by federicoballarini**
Print the total of users and groups in Cockpit interface.
Refer to https://github.com/NethServer/dev/issues/6443

### CODE REVIEW

**Comment by edospadoni** [comment]
Following Patternfly's guidelines, it's better to add the number of a particular list next to the search box like here:
Screenshot from 2021-03-01 09-08-35

In the specific case of the Users and Groups page, the search box acts dynamically based on the type of filter:
Users:
Screenshot from 2021-03-01 09-10-42
Groups:
Screenshot from 2021-03-01 09-10-54

So we can add the number of users or groups next to the search box once for Users (in case "Users" type is selected) once for Groups (in case "Groups" type is selected).

**Comment by federicoballarini** [comment]
@edospadoni what do you think now? :)

**Comment by edospadoni** [comment]
> @edospadoni what do you think now? :)

Much better now. I prefer to change Users: N and Groups: N to Total: N (for both users and groups) because it looks like a repetition. What do you think?

**Comment by edospadoni** [comment]
> > > @edospadoni what do you think now? :)
> > 
> > 
> > Much better now. I prefer to change Users: N and Groups: N to Total: N (for both users and groups) because it looks like a repetition. What do you think?
> 
> Mmm... I don't know... For clarity it's better to show "Users" and "Groups" in my opinion, but I leave the choice to you :)

In other pages or Cockpit applications we have always used "Total". Let's go with Total also here.

**Comment by federicoballarini** [comment]
Here we are @edospadoni :)

**Review by edospadoni — APPROVED** [review]

**Comment by edospadoni** [comment]
Good job :+1:

**Pull request merged**
