### PR TITLE
ui. fix files download on FF

### PR DESCRIPTION
**Pull request by federicoballarini**
Changed backup download method.
Refer to https://github.com/NethServer/dev/issues/5988

### CODE REVIEW

**Comment by federicoballarini** [comment]
@edospadoni I changed download method as `vpn-ui` but I get a CSP error on FF. CSP seems equal to `vpn-ui` one, but it doesn't work. Can you look if we can fix it?

**Comment by edospadoni** [comment]
> @edospadoni I changed download method as `vpn-ui` but I get a CSP error on FF. CSP seems equal to `vpn-ui` one, but it doesn't work. Can you look if we can fix it?

I have no idea :smile: . It the same problem that I faced weeks ago when I have implemented the download with strange name

**Comment by edospadoni** [comment]
> @edospadoni I changed download method as `vpn-ui` but I get a CSP error on FF. CSP seems equal to `vpn-ui` one, but it doesn't work. Can you look if we can fix it?

I have no idea :smile: . It the same problem that I faced weeks ago when I have implemented the download with strange name.

**Comment by gsanchietti** [comment]
So, we should revert everything and close as wantfix?

**Comment by federicoballarini** [comment]
No, I think I found a solution. I try a commit in a minute.

**Comment by federicoballarini** [comment]
I'm working on it to find a solution. I will update you asap.

**Comment by federicoballarini** [comment]
I can't find out any solution. I think we can close this PR and start testing only `vpn-ui`. Probably there are problems on Firefox, but also on Cockpit main module, because I can't understand why on `vpn-ui` it works fine.

**Pull request closed without merging**
