### PR TITLE
UI to enable the ShellOverrideStatus

### PR DESCRIPTION
**Pull request by stephdl**
https://github.com/NethServer/dev/issues/6074

### CODE REVIEW

**Comment by gsanchietti** [comment]
TODO:

- add missing documentation
- wait implementation of user password change

**Comment by gsanchietti** [comment]
The ShellOverride property will be automatically set along with UserSettingsPage prop.

This PR has been replaced by #239

**Comment by DavidePrincipi** [comment]
I'll try to merge it into #239

**Comment by DavidePrincipi** [comment]
Rebased onto https://github.com/NethServer/nethserver-cockpit/pull/239

**Comment by DavidePrincipi** [comment]
I ran prep-sources on my local VM and ended successfully. @edospadoni, @andre8244 you could merge it.

**Pull request merged**
